sonar.projectKey=BrayanL21_LAB6_IS2
sonar.organization=brayanl21
sonar.projectName=LAB6_IS2
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/tests/**
sonar.tests=tests/
sonar.test.inclusions=**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11